@startuml
title Component Diagram

component View
component PhotoViewModel
component "PhotoDataSource +PhotosDataFactory" as repo
component PhotoService
component NetworkManager
cloud 500pxBackend
database RoomDB

 View -down-> PhotoViewModel
 PhotoViewModel -down-> repo
 repo -down-> PhotoService
 PhotoService -down-> NetworkManager
 NetworkManager -down-> 500pxBackend
 repo -down-> RoomDB: maybe


@enduml