@startuml
title Component Diagram

component View
component PhotoViewModel
component PhotoRepository
component PhotoService
component NetworkManager
cloud 500pxBackend
database RoomDB

 View -down-> PhotoViewModel
 PhotoViewModel -down-> PhotoRepository
 PhotoRepository -down-> PhotoService
 PhotoService -down-> NetworkManager
 NetworkManager -down-> 500pxBackend
 PhotoRepository -down-> RoomDB: maybe


@enduml